# Generated by Django 5.2.4 on 2025-07-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exam_examsubmission_question_answer_studentexam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsubmission',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examsubmission',
            name='student',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], help_text='Enter the correct option number (1-4)', max_length=1),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='ExamSubmission',
        ),
    ]
