# Generated by Django 5.2.4 on 2025-07-14 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_examsubmission_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 14, 11, 35, 59, 687488)),
            preserve_default=False,
        ),
    ]
